### ISSUE TITLE
\forall cofibration

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#102]
I have no idea how to do this --- I am a bit stuck on both the admissible *and* the derivable version. Can @favonia help me?

**Comment by jonsterling** [comment]
I do have a kind of "evil" way to do it. Add it to the syntax but not to the semantics, and then have an evaluation rule that does the following weird thing:

```
eval env (Forall tphi) = 
  let x = Symbol.fresh () in 
  let vphi = eval (DimProbe x :: env) tphi in 
  purge_from vphi x
```

**Comment by favonia** [comment]
What did you mean by "admissible" and "derivable"?

**Comment by jonsterling** [comment]
@favonia By "admissible" I mean the one where you don't make it a generator in the type of cofibrations, and instead try to "implement" it by purging some disjunctions... By derivable, I mean making it a generator. The latter is probably a bad idea, because the left-inversion based proof search would not work.

**Comment by favonia** [comment]
We need to revisit our theory and normalization results.

**Comment by jonsterling** [comment]
I agree
