### ISSUE TITLE
REPL command deliminator

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#108]
What should be the delimiter between top-level commands, if any?
```
normalize 5;
```

```
normalize 5;;
```

**Comment by jonsterling** [comment]
In case it helps, I may wish to use `;` at some point in the tactic language. I would be ok with `;;` as an *optional* delimiter for toplevel commands, that is looked for when using an interactive interface.

Also open to alternatives; I am even open to a _non-ugly_ mandatory separator.

**Comment by favonia** [comment]
@jonsterling
```
normalize 2 ⸎
normalize 2 ⨾
normalize 2 ⨟
```

**Comment by jonsterling** [comment]
How about some cool kind of white space character LOL

**Comment by favonia** [comment]
Like this?
```
normalize 2 
```

**Comment by favonia** [comment]
> How about some cool kind of white space character LOL

Be careful about what you are wishing for...
