### ISSUE TITLE
tactics interface

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#115]
Consolidation + renaming

- [ ] T.chk_tac -> T.Chk.tac
- [ ] T.bchk_tac -> T.BChk.tac
- [ ] T.syn_tac -> T.Syn.tac
- [ ] R.Univ.path_with_endpoints -> R.Univ.path

**Comment by ivoysey** [comment]
Re. "R.Univ.path_with_endpoints -> R.Univ.path", for what it's worth, there is also an R.Univ.path at a different type
