### ISSUE TITLE
Design to "bubble up" cofibration splits

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#128]
We need a design for pushing operations through cofibration splits during evaluation; roughly any part of the evaluator that matches on a value is something that needs to commute with the splits --- currently there are edge cases that are not dealt with.

A good way to test if an idea is too naive to help is, does it explain how to deal with `coe {i => [phi => A i * | psi => B i *]}` as well as `fst [phi => M * | psi => N *]`?

**Comment by jonsterling** [comment]
It would be worth considering the monads that are used in nbe of strict booleans (as in the recent work of Abel and Sattler); this is roughly analogous to the CPS transform of Filinski (?) for the same purpose.

I think conceptually there is no barrier to a smart approach, but there is some difficulty coming from the need for type annotations on splits. At the places where we want to create a new split, we may not have enough information to annotate them correctly. It may be that the right thing to do is make the type information much more pervasive (and also require a type argument to `eval`).

**Comment by favonia** [comment]
I think the `fst` you brought up should also be listed as a Thought test, because the eventual type of the outermost split is more "known" in the `coe` case than the type of the application of `fst` to something of type `[phi => A * B | psi => something random]`.

**Comment by favonia** [comment]
Let me propose the cofibration-indexed list monad `(cof * 'a) list` for the evaluator.

**Comment by jonsterling** [comment]
I do not think this monad thing will work, because of type annotations, and I believe it may be 1000% more invasive to evaluation than my proposal, which is to maintain the invariant that evaluation be happening wrt a reduced cofibration environment.

I'm open to the idea in general, but based on our discussion it seems like there is no reason to believe it could be made to work without some very brutal type annotation scheme.

**Comment by jonsterling** [comment]
It is important to remember that the `Refiner` / `Elaborator` must _not_ be in this list monad, because we don't want to execute a tactic ten times (the reason is not efficiency, but rather that a user does not expect to receive ten versions of the same hole). But the refiner calls the evaluator, so I see this as a dead end unless some more refined design is proposed.

What I am proposing is instead to maintain the invariant in `Quote` that `eval` is called with a reduced cofenv, and in `Quote` to split whenever the cofenv becomes unreduced. The type information that we have at these points in the program is sufficient to produce the split.

**Comment by favonia** [comment]
Okay I think the hole issue killed it. BTW I think we miscommunicated LOL but gladly we are on the same page now.

**Comment by jonsterling** [comment]
I'm going to close this ticket (thanks to #125); there are still some edge cases in refinement to consider, but I think we could track those more specifically as they arise.
