### ISSUE TITLE
GitHub Actions broken lol

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#132]
https://github.com/RedPRL/cooltt/runs/731175503

**Comment by favonia** [comment]
Yeah please ignore it.

**Comment by favonia** [comment]
I guess they accidentally removed the m4 macro processor from the image. :facepalm: Anyways it's not our problem.

**Comment by jonsterling** [comment]
🤦 LOL

**Comment by favonia** [comment]
Let me close this issue because there's nothing we should do! LOL

**Comment by favonia** [comment]
Reported: https://github.com/actions/virtual-environments/issues/985

**Comment by cangiuli** [comment]
It's working again. @jonsterling can you turn CI requirement back on?

**Comment by jonsterling** [comment]
done! thanks!
