### ISSUE TITLE
Factor out the frontend into a (local) library

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#160]
Would be nice for cleanup purposes and for facilitating documentation!

**Comment by ivoysey** [comment]
@jonsterling Yeah this is a refactor that should happen for sure. At the moment I definitely appreciate not making this exact merge nightmare for me; are you feeling relatively patient with this block?

**Comment by jonsterling** [comment]
Yes, I definitely don't want to cause some merge nightmares!
