### ISSUE TITLE
Add "weak truth" type for cofibrations (cool way to handle opacity)

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#175]
Given `phi : F`, let's add a type `true(phi)` for *non-reflected* truth of `phi`. I will motivate this after explaining the rules.

1. Intro rule: obvious
2. Equality: proof irrelevant
3. Elim rule: `x : phi <- M; N` when `M:true(phi)`, and `N` assumes `phi = true`.
4. Commuting conversions: the elim disappears if `phi` is already true, and otherwise, definitional equivalence checking will just push it upward.

What is the purpose of this? It gives us a good way to implement opacity. Every top-level declaration `foo` can generate a fresh cofibration `phi/foo` together with a top-level assumption `true(phi/foo)`; then the declaration of `foo` remains abstract, but has an extension type governed by `phi/foo`. Then `unfold foo in M` would elaborate to  `_ <- phi/foo; M`.

Notes: this is a form of opacity that hides information from definitional equivalence; the existing one in cooltt reveals all to def.eq. but hides from display. Both notions are useful, but we might want to rename the existing `unfold` to `reveal` or something?? Or maybe the other way around? Not sure.

@cangiuli @favonia

**Comment by jonsterling** [comment]
I'm not sure this makes sense... The strong rules of definitional equivalence seem to make the wrapped and unwrapped versions isomorphic, but if this is the case, then the theory actually already implies `x : true(phi) !- phi = (0=0)`, so we have the reflection whether we want it or not.

**Comment by favonia** [comment]
What's the mechanism to introduce the top-level assumption `true(phi/foo)`?

I slightly prefer keeping unfold as it is (that is, no-op with respect to judgmental eq) and have a new modaltiy-like syntax/mechanism for opaqueness.

**Comment by jonsterling** [comment]
OK, I see what needs to be done --- it is important to *not* make these isomorphic. This in particular that def.eq. might get stuck on different locations of the `unfold` expression, but that all such problems can be resolved using another `unfold` --- presumably this could be handled by the elaborator.

**Comment by jonsterling** [comment]
@favonia So, my thinking is that these are indeed two separate mechanisms and we should have different names for them. But I think the idea would be that for the real opacity, there could be three levels:

1. Totally transparent: this means that the `def` unleashes `phi/foo = true`.

2. Conditionally transparent: this means that the `def` unleashes `true(phi/foo)`, and the user must eliminate that assumption when they want to expose the definitional equality.

3. Totally opaque: this means the `def` does not even unleash `true(phi/foo)`.

**Comment by favonia** [comment]
I don't think there's much difference between 2 and 3 in "real" implementation. You could introduce `true(some/global/phi/that/is/so/secret/that/you/cannot/even/imagine)` for everything in category 3 to guard it.

**Comment by favonia** [comment]
Actually, for uniformity, category 1 is true(#t) and category 3 is true(#f). Maybe it would be fun to let users enter and exit different modes (that is, the sets of phis in the prefix)? The "lock" would be `true(phi1 /\ phi2 /\ phi3)`, for example.

**Comment by favonia** [comment]
@jonsterling I think our minds are synchronized through some low-tech telepathy. For the naming issue, I propose 🤮/puke as the alternative syntax no matter what the serious syntax is. Examples:
```
{🤮 phi/foo in M}
```

**Comment by jonsterling** [comment]
Btw it is very important that we _don't_ have some strong definitional equivalences for `unfold/unleash`... One equation I'd considered, equivalent I think to some maximal commuting conversions, was: `(unleash[phi] u as z in v(z)) == w` if `phi !- v(*) == w`. But this makes every term equal to its unfolding _without_ any explicit unleashing! Bad.

So, I think it is only OK to have some weak equational theory on `unleash`, as outlined in the secret note.

**Comment by jonsterling** [comment]
My new pull request #176 is adding the features to the top-level context needed to support the extension by a fresh cofibration, etc., as a preliminary toward implementing this.
