### ISSUE TITLE
Add Record Types

### ISSUE THREAD

**Issue by TOTBWF** [RedPRL/cooltt#188]
It would be handy to have records, so that we could avoid situations like `isos.cooltt`:
```
def iso/trans (A : type) (B : type) (C : type) (I1 : iso A B) (I2 : iso B C) : iso A C :=
  let f1 := fst I1 in
  let g1 := fst {snd I1} in
  let α1 := fst {snd {snd I1}} in
  let β1 := snd {snd {snd I1}} in
  let f2 := fst I2 in
  let g2 := fst {snd I2} in
  let α2 := fst {snd {snd I2}} in
  let β2 := snd {snd {snd I2}} in
  [a => f2 {f1 a}, 
   [c => g1 {g2 c}, 
    [c => trans C {j => f2 {α1 {g2 c} j}} {α2 c},
     a => trans A {j => g1 {β2 {f1 a} j}} {β1 a}]]]
```

**Comment by jonsterling** [comment]
That's a great idea!

**Comment by jonsterling** [comment]
Would love to hear your ideas about how record types should be designed; we could work together on ironing it out :)

**Comment by TOTBWF** [comment]
As a starting point, it feels like a good call to just consider the simple case where we only have non-inductive records. It also might be a good call to require a constructor for records, as it lets us sidestep a bunch of hairy questions about eta rules.

There's also the question of how we handle field projections. The lazy thing to do would be to just add the field projections as functions `sel : record -> field` to the namespace, but you end up paying for this laziness by having to avoid ever using the same selector name twice, which is not exactly ergonomic. Therefore, I'm leaning towards an Agda-Style "Records as Modules", which seems to solve these problems at the surface level. Then, in the semantics, we can just work with fully qualified names at all times.

The Kan operations will be a bit gnarly to write, but hopefully won't be _too_ bad? We should definitely pay attention to how we handle goal display involving records though, as this can get brutal once the record gets large enough.

**Comment by TOTBWF** [comment]
As an aside, it's probably worth thinking about _some_ sort of module system here, as both records and modules bring up some hairy questions about namespacing, so it's probably best to do these things in one fell swoop.

**Comment by cangiuli** [comment]
We might not actually need Kan operations in the first cut. A recurring issue in HoTT developments is that characterizing the hlevels of various objects (e.g., equivalences) is easiest to do by appealing to general lemmas about sigma types. As a result, one already switches away from a record to prove some of the basic theory, so it may be not be such a big issue for records to not be Kan (as long as the types of the projections are Kan when appropriate!!).

**Comment by cangiuli** [comment]
(Just to clarify, my message assumes that we have a Kan sigma type in addition to records. If we wanted to delete sigma types entirely, we would indeed want records to be Kan.)
