### ISSUE TITLE
🛐 Adopt type atom = [L of int | G of Symbol.t]

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#196]
I think it is good to increase uniformity across `Cof`, `Dim`, and universe levels.

**Comment by favonia** [comment]
Close this now until further refactoring.

**Comment by ice1000** [comment]
Does "Worship ``type atom = [`L of int | `G of Symbol.t]``" work in the issue title?

**Comment by ice1000** [comment]
Oh I guess no🤣
