### ISSUE TITLE
⚙️ SMT for deciding cofibrations

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#197]
The basic idea is to use SMT solvers in replace of `cubical.CofThy`. See the latest comment for the template.

**Comment by favonia** [comment]
Side notes: the `pop`/`push` commands might help us navigate terms under different constraints without starting from scratch every time.

**Comment by favonia** [comment]
There was a typo---I forgot to add the assertions `distinguished != 0` and `distinguished != 1`.

**Comment by favonia** [comment]
Updates: perhaps we do not need `distinguished` at all! At least for the fragment without negation.

**Comment by jonsterling** [comment]
@favonia This stuff seems potentially very immortal... For negation it seems like we should just add function constants for both the positive and negative version of an atomic cofibration-function. As in the following example:

```smt
(set-logic UF) ; setting sublogic for potential efficiency. UF stands for "Uninterpreted Functions"
(declare-sort I 0)
(declare-const one I)
(declare-const zero I)
(assert (distinct one zero))
; sorts
(declare-const r I) 
; context

(declare-fun phi (I) Bool)
(declare-fun negphi (I) Bool)
(assert (forall ((i I)) (=> (and (phi i) (negphi i)) false)))
(assert (negphi r))

; =====> 
(assert (not (phi r)))
(check-sat) ; unsat => (phi r) is true; sat => not conclusive

;; RESULT: sat
```

Regarding the inconclusive results, we probably need more precision than that for the implementation. That is, we need to know conclusively that some sequent doesn't hold in order to proceed in the code. Do you think we are working in a fragment that SMT is complete for?

**Comment by favonia** [comment]
Makes sense. Did you prove the reduction?

> Regarding the inconclusive results, we probably need more precision than that for the implementation. That is, we need to know conclusively that some sequent doesn't hold in order to proceed in the code. Do you think we are working in a fragment that SMT is complete for?

I think so. So for `p |= q` we can test both `q` and `not q`.

**Comment by favonia** [comment]
BTW, I have some suggestions/questions

1. Shouldn't `phi` or `negphi` be indexed by something other than `I`, say a different sort `F`? I know it's working now...
2. If we want to recycle `I`, how about this:
```smt
(define-fun phi ((i I)) Bool (= i one))
(define-fun negphi ((i I)) Bool (= i zero))
```
Disclaimers: I did not prove anything.

**Comment by jonsterling** [comment]
I don’t think i understand your phi functions. I was thinking of these being propositions that range over a dimension, but you seem to be doing something different. am i confused?

**Comment by favonia** [comment]
New Thought One: perhaps using the interval to (hopefully) simulate the solver for intuitionistic logic (inspired by https://arxiv.org/pdf/1809.00393.pdf)

```smt
(define-const bot Real 0.0)
(define-const top Real 1.0)
(define-fun land ((i Real) (j Real)) Real (ite (<= i j) i j))
(define-fun lor ((i Real) (j Real)) Real (ite (<= i j) j i))
(define-fun arrow ((i Real) (j Real)) Real (ite (<= i j) top j))
(define-fun neg ((i Real)) Real (arrow i bot))
(define-fun istrue ((i Real)) Bool (= i top))
; sorts
(declare-const r Real)
(assert (<= bot r top))
; context
; =====>
(define-const goal1 Real (lor r (neg r)))
(check-sat-assuming ((not (istrue goal1))))
(check-sat-assuming ((istrue goal1)))
(define-const goal2 Real (neg (lor r (neg r))))
(check-sat-assuming ((not (istrue goal2))))
(check-sat-assuming ((istrue goal2)))
(define-const goal3 Real (neg (neg (lor r (neg r)))))
(check-sat-assuming ((not (istrue goal3))))
(check-sat-assuming ((istrue goal3)))
```

New Thought Two: we can embrace a stronger algebra and define `(= x y)` to be `dist(x,y)`

**Comment by favonia** [comment]
Related work:
- https://arxiv.org/pdf/1809.00393.pdf
- http://www.csl.sri.com/users/sgl/Work/Reports/2019-07-G4-SMT-Tableaux19.pdf

**Comment by favonia** [comment]
I'm no longer interested in this development.
