### ISSUE TITLE
📶 Streams for universe levels

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#198]
(This was initiated by @jonsterling's and then Visualized by @favonia.) Conor McBride's crude stratification essentially parametrizes every definition with one single universe level. It avoids solving inequalities but also makes it challenging to insert new universe levels between two adjacent levels used in prior definitions. A remedy is to consider a wider class of monotone endofunctions on natural numbers instead of just `(+ n)`. The class must be closed under function composition. A seemingly working version is to consider monotone functions `f` such that `f(n) = n + c` for some constant `c` for large enough `n`.

An endofunction on natural numbers can be represented as an infinite stream. During the preliminary experiments, representing such streams by the increments between adjacent numbers seems to work better than using the numbers directly. For example, consider the function
```
f(0) = 10
f(1) = 20
f(2) = 22
f(3) = 23
f(4) = 25
f(n) = 22 + n for n > 4
```
The stream is
```
10, 20, 22, 23, 25, 27, 28, 29, ...
```
The increments are
```
10, 2, 1, 2, 2, 1, 1, 1, ... (forever 1)
```
And the proposed representation is `(10, [2;1;2;2])` in OCaml, where `10` is the first number and the implicit infinite suffix of number `1` is not encoded. (The invariant is that the last element of the second component in the representation must be greater than one.) The suggested change to `src/core/ULvl.mli` (after #195) is the following:
```ocaml
type shift = {init: int; steps: int list} (* named tuples for more sanity *)

type t =
  | LvlShiftedVar of {var: int; shift: shift}
  | LvlShiftedGlobal of {sym: Symbol.t; shift: shift}
  | LvlTop
```
The identity function is `{init=0;steps=[]}` and the traditional `+ n` functions are `{init=n;steps=[]}`. Every function in the class has a unique representation.

The prototype shows that it's almost trivial to implement these streams by introducing a new frame `KShift` in the domain and a new construct `LvlShift` in the syntax, unless we wish to include `TpShift` and bring level shifting to the logical framework. With `TpShift`, it seems we are allowing higher-order reasoning with function symbols, and applications of such generalization remain unknown.

**Comment by jonsterling** [comment]
Can you say what `TpShift` is operationally or semantically? Just to help my brain a bit.

**Comment by favonia** [comment]
> Can you say what `TpShift` is operationally or semantically? Just to help my brain a bit.

It is like `TpLvl`, `TpDim`, and `TpCof`, where we internalize them into the framework.

**Comment by jonsterling** [comment]
ah, thanks!

**Comment by favonia** [comment]
Already implemented by the mugen package.
