### ISSUE TITLE
☯️ Primitive negation

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/cooltt#200]
Favonia asked me to write down this half-baked observation. I don't know whether it is relevant to you.

Some context first. Andrea Vezzosi's trick for ensuring composites with empty systems don't arise is to add an additional face at the negation of the tube cofibration, like so:
```
ghcom A 0 1 φ {i _ => [ i=0 => c | φ => t]}
~becomes~>
hcom A 0 1 {φ ∨ ¬φ} {i _ => [ i=0 ∨ ¬ φ => c | φ => t]}
```
For this, we need to have a negation operator on cofibrations, the essential properties for the "trick" being that (a) `φ ∧ ¬ φ` is false (b) `φ ∨ ¬ φ` is true whenever `φ` contains no interval variables.

In Cubical Agda, this is achieved by using the interval object instead of some subobject of Ω as the cofibration classifier: the De Morgan interval has a reversal operation that can serve as negation. But this is perhaps weird. (Digression: we _could_ do it in cartesian type theory, using a De Morgan interval-like object as the cofibration classifier; nothing requires it to be the 'actual' interval.)

We can instead try to put in a primitive negation operator in our cofibration language. One thing to check is that we can still eliminate `∀`. The observation is just that the presheaf semantics justifies the following equivalence to handle the `¬` case:

`∀i:𝕀. ¬φ(i)` ⇔ `¬φ(0) ∧ ¬φ(1)`

This follows from the equivalence  `¬¬(r=0 ∨ r=1)` ⇔ `⊤`, which we might separate into
`¬(r=0)` ⇔ `r=1` and   `¬(r=1)` ⇔ `r=0`.

But I don't know how easy it is to check cofibration equality for the extended language, nor if this would work well with cofibration variables.

**Comment by favonia** [comment]
Sorry I did not mean to force you to Unleash the Thought. I think it is (equally) easy to check equality and variables are all fine! In other words, everything is Visualized.

**Comment by favonia** [comment]
BTW, the equation must hold for any reasonable definition of `¬`, because (assuming reasonable semantics):

`⊤` ⇔ `¬⊥` ⇔ `¬(r=0 ∧ r=1)`

and thus

- `¬φ` ⇔
- `¬φ ∧ ⊤` ⇔
- `¬φ ∧ ¬(r=0 ∧ r=1)` ⇔
- `¬(φ ∨ (r=0 ∧ r=1))` ⇔
- `¬((φ ∧ (r=0)) ∨ (φ ∧ (r=1)))` ⇔
-  `¬(φ ∧ (r=0)) ∧ ¬(φ∧(r=1))`

**Comment by jonsterling** [comment]
Nice observation! Just to say, there is only one definition of `¬`, the one that you get from the Kripke-Joyal semantics. And it indeed has the properties you describe. 

This is all very interesting because it kind of seems that negation is almost admissible except on cofibration constants, which suggests that we almost immediately have a good algorithm.

Does this totally kill the empty systems? A priori I don't see how it does, but I might be missing something.

**Comment by favonia** [comment]
> Does this totally kill the empty systems? A priori I don't see how it does, but I might be missing something.

Almost---this means g(h)com can be defined for almost any cubical type theory, but does not mean g(h)com can be collapsed with (h)com with some other changes you may or may not want.

**Comment by jonsterling** [comment]
Sorry, let me be more explicit. I felt basically one wants to be able to replace a proposition by one that can never become false, i.e. for which `~~phi` holds in the "presheaf sense". But you are replacing `phi` by `phi \/ ~phi`, but it's not the case that `~~(phi \/ ~phi)` holds, is it?

**Comment by favonia** [comment]
`¬¬(phi \/ ¬phi)` always holds (assuming you are not redefining any symbol LOL).

**Comment by jonsterling** [comment]
Oh ok, then good! Sorry I am just waking up and hadn't fully activated my 🧠

**Comment by jonsterling** [comment]
Then this is great! I think it's amazing that we didn't think of this before... 😆 Could have saved us a lot of trouble when coding the brutal ghcom algorithm haha

**Comment by favonia** [comment]
The current solver is wrong.

**Comment by favonia** [comment]
Not currently planned.
