### ISSUE TITLE
add dune task for ocp-indent?

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#208]
I don't know how to do this, but it would be cool.

**Comment by favonia** [comment]
Git pre-commit hooks might be easier?

**Comment by jonsterling** [comment]
Well I don't think I want a commit-hook, but I would be happy with a script that I can run haha.

**Comment by favonia** [comment]
Well, you can just run...
```sh
find src -regex '.*\.mli?' -exec ocp-indent {} --inplace \;
```
Warnings: ocp-indent seems to (re)write the files even when nothing has been changed.

**Comment by jonsterling** [comment]
This command doesn't work on macOS due to differences in how `find` interprets regexes. Unfortunately, the fix is also not portable...

**Comment by jonsterling** [comment]
This command looks like it might be more portable:

```
git ls-files | grep -E ".*\.ml(i|l|y)?$" | xargs -I% bash -c 'ocp-indent -i %'
```

**Comment by favonia** [comment]
> This command doesn't work on macOS due to differences in how `find` interprets regexes. Unfortunately, the fix is also not portable...

The real fix is `brew install findutils` :smirk:
