### ISSUE TITLE
🪡 Record patching (like SML `where type`)

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#266]
I want to support record patching as in SML's `where type` construct. There are a lot of anomalies involved in the SML construct, however, which has led to a proliferation of mutually incompatible semantics, each of which has something to argue for it. I think that by taking a type theoretic point of view, we can arrive at something that is quite workable, however.

Consider the following record type: `EL := sig {A : type; a : A}`. In this case, it makes sense to speak of patching `EL | A .= nat` or something like this, but what would it mean to patch `EL | a .= 4`? This doesn't make type sense because the value of the `a` field is not even typable without the prefix of the record in scope. While there are a variety of ways to deal with this, I think the _best_ way is to just bring the prefix into scope. Therefore, in a patch `EL | a .= XXX`, the type of `XXX` would actually be `(self : sig {A : type}) -> self.A`.

We must extend the above to account for multiple patches in a cascade of dependencies... In a patch `EL | A .= XXX | a .= YYY`, the type of `XXX` would be `(self : sig {}) -> type` and the type of `YYY` would be `(self : sig {A : sub type #t {XXX {struct {}}}}) -> self.A` which is definitionally equal to `(self : ...) -> XXX {struct {}}`. The resulting patch would be:

```
sig {A : sub type #t {XXX {struct {}}; a : sub {XXX {struct {}} #t {YYY {struct {A := A}}}}
```

Obviously the notation needs some work. I don't know if we should implement a unary patch operator and derive the multi-patches from this by iteration, or if it is better to have some kind of multi-patch operator. Ideas are welcome.

## Non-singleton patching
It is possible to also consider versions where we patch against a cofibration other than `#t`. While the version where we patch against `#t` is clearly Kan and can therefore be incorporated into the universe (because it just involves turning some things into singletons), the version where we patch against an arbitrary cofibration will not always be Kan, so it would only live in the outer layer. I propose to support only the singleton patching for now, because it covers the biggest use-cases involved in moving from an overly parameterized to a fibered programming style.

## Functional example

```cooltt
(M : monoid) (A : group | car .= self => m.car) -> ...
```

In the above, the `self` variable probably has the nullary record type `sig {}` because `car` is the first field of `group`! I think in the user-facing language we might make this variable hidden and treat `self` as a magic keyword that is resolved in this context.

**Comment by favonia** [comment]
Some possible syntax to consider:
```
EL 🤳 x | A .= ...... | a .= .... x.A ...
```
Once we have implemented it, we can try to support non-Unicode-speaking people by allowing
```
EL as x | A .= ...... | a .= .... x.A ...
```

**Comment by TOTBWF** [comment]
After toying around with this a bit, it seems like it might be a little easier to use extension types rather than subtypes, as we can have codes of them.
