### ISSUE TITLE
📥 Support for auto-converting between fibered and parameterized type families

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#267]
As part of my long-term program to eliminate some of the basis for wanting unification, I want to support auto-converting between type families and their total spaces in a very convenient way. I think Arend has a feature like this, but let me give my version.

Given a family of types `F : sig {fields...} -> type`, we may consider the record type `sig {fields...; fib : F {struct {fields...:= fields...}}}` if you know what I mean. In essence, I would like to implicitly write `F` also for the latter record type. This interacts in a beautiful way with the proposal for record patching #266 to enable the following code:

```cooltt
def category :=
  sig
    ob : type
    hom : sig {s : ob; t : ob} -> type
    idn : (x : ob) -> hom | .s = x | .t = x
    seq : (f : hom) (g : hom | .s = f.t) -> hom | .s = f.s | .t = g.t
    seqL : (f : hom) -> path {hom | .s = f.s | .t = f.t} {seq {idn f.s} f} f
    seqR : (f : hom) -> path {hom | .s = f.s | .t = f.t} {seq f {idn f.t}} f
    seqA : (f : hom) (g : hom | .s = f.t) (h : hom | .s = g.t) -> path {hom | .s = f.s | .t = h.t} {seq f {seq g h}} {seq {seq f g} h}
```

The equivalent code without this feature would result in an EXPLOSION of parameters that must be passed to everything. Indeed, that explosion is one of the biggest reasons that implicit parameters are important in dependent type theory --- but our packed/fibered representation is much more elegant and reliable.

It is also worth noting that it would have type checked to write `seqL : (f : hom) -> path {hom} {seq {idn f.s} f} f`, but this would be mathematically very wrong! Because it allows to include a symmetry on the boundary of the morphism `f`. I think the fact that you can choose to allow or not allow this depending on how much you specify the type makes sense, but it is worth noting as one potential way that a user could injure themselves.

**Comment by favonia** [comment]
POSIX shell style to convert F to its total space: `F {@}`. Reference: [2.5.2 Special Parameters](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_02)

**Comment by jonsterling** [comment]
> POSIX shell style to convert `F` to its total space: `F {@}`. /s
> 
> > Reference: [2.5.2 Special Parameters](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_02)

lmao I kind of love this

**Comment by favonia** [comment]
> > POSIX shell style to convert `F` to its total space: `F {@}`. /s
> 
> lmao I kind of love this

LOL I think someone made a Wish. A more concrete proposal that goes with #266:
```
hom {@ | .s = f.s | .t = f.t}
hom {@ as x | .s = f.s | .t = x.s}
X | .A = x 
X as x | .A = foo | .a = x.b
```

**Comment by favonia** [comment]
Already implemented.
