### ISSUE TITLE
A flat modality for the LF

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/cooltt#32]
To implement a number of things properly, it will be useful and/or necessary to have a `flat` modality; it is OK if it is restricted to occur as an argument to a pi type, which often simplifies matters --- these kind of types are called "virtual" in cooltt, and include `dim,cof` as well.

**Comment by jonsterling** [comment]
@mweav We can track discussion of this idea in this ticket.

**Comment by jozefg** [comment]
I suspect that if it's easy to implement flat in a virtual way, it would be easy to internalize it as a connective with the pattern-matching eliminator we use in MTT. This was more or less the progression of things with Andreas's work on degrees of relatedness iirc.
