### ISSUE TITLE
⛳ Show numbers of holes

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#344]
This is to address the usability issue in #339.

**Comment by favonia** [comment]
@jonsterling I know you are not picky, but I wonder if you have any preference about where to show unsolved holes (or meta variables in general). I intend to show the total number of silent and "voluble" (?) holes because, in terms of correctness, their damage seems to be the same. Should we display the message at the end of a definition, a unit, or a section? Any preferences? @cangiuli @TOTBWF The messages in my mind would be

```
[Error] There are 3 unsolved holes.
```

```
[Error] There is 1 unsolved hole.
```

**Comment by jonsterling** [comment]
Your messages are fine but i would treat it as a warning rather than an error

**Comment by jonsterling** [comment]
my original thought was at the end of the unit, but section or even definition seems ok too.
