### ISSUE TITLE
:no_good: <Something> should not compare names

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#377]
In #376, it was discovered that \<something\> might be comparing names in Global.t that should be used purely for printing.

@jonsterling Seriously, what's wrong with us!!! :laughing:

**Comment by jonsterling** [comment]
i couldn't figure out where this is happening... a bit bizarre

**Comment by jonsterling** [comment]
I can confirm that conversion is not comparing names: https://github.com/RedPRL/cooltt/blob/main/src/core/Conversion.ml#L413

So it must be happening somewhere else... 😦

**Comment by favonia** [comment]
It could also be that we accidentally wrote `sym0 = sym1` somewhere :scream:

**Comment by favonia** [comment]
The `kado` library looks okay. :thinking:

**Comment by jonsterling** [comment]
What about compare?

**Comment by favonia** [comment]
> What about compare?

https://github.com/RedPRL/kado/pull/10 :rofl:

**Comment by favonia** [comment]
@jonsterling Okay, I think it's this line?

https://github.com/RedPRL/cooltt/blob/7408368d8ee0076780f96e0907e959b31351cb65/src/core/Dim.ml#L13
