### ISSUE TITLE
Nix Flake: No matching version for bwd >= 2.1

### ISSUE THREAD

**Issue by solomon-b** [RedPRL/cooltt#400]
I'm trying to generate a nix shell and am running into dependency issues:

```
➜ nix develop --impure
error: builder for '/nix/store/rbhnf7xzvx5ib2z3469vxjvr2by0qs2y-resolve.drv' failed with exit code 20;
       last 5 log lines:
       > [ERROR] No solution including optional dependencies for cooltt.0.0 & ocaml-base-compiler:   * Missing dependency:
       >             - bwd >= 2.1
       >             no matching version
       >
       >
       For full logs, run 'nix log /nix/store/rbhnf7xzvx5ib2z3469vxjvr2by0qs2y-resolve.drv'.
(use '--show-trace' to show detailed location information)
```

**Comment by favonia** [comment]
@solomon-b Sorry that we didn't respond. I can confirm that the nix installation has this issue. Unfortunately I don't know how to fix it. :crying_cat_face:

**Comment by solomon-b** [comment]
@favonia i actually managed to get past this issue in [PolyTT](https://github.com/toposInstitute/polytt) by using Opam-Nix:
https://github.com/ToposInstitute/polyhack2023/blob/main/flake.nix

It should be pretty much directly re-usable for CoolTT as PolyTT uses all the same RedPRL family of libraries. We even have a successful nix build.
