### ISSUE TITLE
User-friendly pretty printer

### ISSUE THREAD

**Issue by ivoysey** [RedPRL/cooltt#66]
this can be a real rabbit hole but i think these are increasing order of preference for me:

```
_x₁ : (prf (or (= _x 0) (= _x 1)))
```

```
_x₁ : prf (_x = 0) ∨ (_x = 1)
```  

```
_x₁ : prf (_x = 0 ∨ _x = 1)
```

**Comment by jonsterling** [comment]
I suggest that instead of adding some kind of scary special cases to what is a pretty uniform core language notation, I suggest that we add a pretty printer that outputs readable code (not s-expr!) that can be understood by the user. I haven't ever done this because it has always seemed so difficult, but if you have any ideas I would welcome them.

**Comment by ivoysey** [comment]
yeah i know this is a real rabbit hole for sure, and have no interest in horking up the internal language.

**Comment by cangiuli** [comment]
I agree with Jon -- it should either be s-expressions or something that looks like the surface language. One thing that would make the current output way more readable to me would be if we could remember the "original" names of variables when that makes sense. I recall that in RedPRL we had a fancy scheme for printing modifications of the original names that avoided shadowing.

**Comment by jonsterling** [comment]
Forgetting about names for a moment, if we want to have a "user-friendly" pretty printer (as I've renamed the ticket), we will need to have some code that computes whether you need to parenthesize something based on precedence, etc.

Once upon a time I had written such a code, and I think I based it on stuff that the Twelf crew did even more "back in the day"... Anyway, just to provide a picture of what is needed.

Now, I have no idea what to do about having output code get indent in a reasonable way, but I guess someone can figure this out.

**Comment by jonsterling** [comment]
Ugh I just was doing some experimentation with this and then I "git reset --hard" by accident. Cool.

**Comment by ivoysey** [comment]
honestly, it would surprise me a little bit if no one had written a little ocaml library for pretty-printing s-expressions in a semi-sane way that we could try to hijack. i'll look into that at least.

**Comment by jonsterling** [comment]
Well, hold on a moment --- we don't need help pretty-printing s-expressions! We've already got that part down easily (that's what the current code does).

The thing we need help with is printing anything other than s-expressions.

**Comment by ivoysey** [comment]
erh. yeah, i misspoke. i guess i meant, more generally: we can't be the first people to have this problem.

**Comment by jonsterling** [comment]
I saw some library that helps, but it looks unmaintained. Anyway, my perspective is that the first thing to do is design what we want it to do (like, what the output should be) and then coding it (using a library or using ourselves) is a secondary matter that can just be carried out.

**Comment by jonsterling** [comment]
In the past I've implemented very powerful and extensible pretty printing libraries (for SML for instance) but I would love there to be some simpler / less high-powered approach --- for instance, one that relies mostly on the builtin box format combinators of OCaml. That might be a pipedream haha.

**Comment by jonsterling** [comment]
By the way, I have some pre-thoughts about this that I want to take the time and think out.

**Comment by ivoysey** [comment]
same

**Comment by ivoysey** [comment]
for what it's worth, even just this output as of this morning's merges and me recompiling everything is like 90% of what i was thinking anyway:
```
test/path-types.cooltt:7.9-7.10 [Info]:
  Emitted hole:
    A : (_x : 𝕀) → univ
    a : A 0
    b : A 1
    _x : 𝕀
    _x₁ : [{_x = 0} ∨ {_x = 1}]
    _x₂ : [_x = 0]
    |- ? : A 0
```
