### ISSUE TITLE
Refactor cof checking to Favonia's liking 😜

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#80]
~~@jonsterling @ivoysey Do we have to remember why the environment is inconsistent? Could we drop `env.cof` and use this instead?~~

This proposal is so dumb. Let's ignore it for the moment.

**Comment by ivoysey** [comment]
I'm not sure what the context you have in mind for this question is; maybe you could elaborate or point to a call site or whatever. Mostly I've relied on calling `test_sequent` to make this kind of logic happen, as in https://github.com/RedPRL/cooltt/blob/master/src/lib/Quote.ml#L46

**Comment by jonsterling** [comment]
@favonia I don't understand 100% of the question, but at least I can tell you that we don't care why the env is inconsistent --- once it's inconsistent, we stop looking at it in any substantive way.

**Comment by favonia** [comment]
If we merge #85, I am not sure if we should close this issue. There might be some tweaks we can make about those `unreduced_joins`, but honestly I don't want to touch the code for at least one week.

**Comment by jonsterling** [comment]
I prefer to close the ticket when this is merged, and further issues can have a new ticket that is more descriptive.

**Comment by favonia** [comment]
(My politeness did not work!!! @jonsterling)
