### ISSUE TITLE
multi-lambdas and el

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/cooltt#89]
This came up when experimenting with changing `path` to `pathd`. The following code type-checks:

```
def pathsimple : {
  (A : type) → A → A → type
} = {
  λ A x y => path {λ _ => A} x y
}

def refl : {
  (A : type) → (x : A) → pathsimple A x x
} = {
  λ A x => λ i => x
}
```

However, if I try to write `λ A x i => x` in `refl` instead, I get: `Head connective mismatch, expected pi but got el! {pathsimple A x x}`.

**Comment by jonsterling** [comment]
Ah, it looks like someone needs to `whnf` the goal somewhere.
