### ISSUE TITLE
Use sedlex (or any Unicode-friendly lexer)

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#93]
I guess the parser is counting the bytes in UTF-8.

**Comment by jonsterling** [comment]
I guess we need to replace the lexer. How did we not notice this in redtt though??

**Comment by favonia** [comment]
A possible choice is [sedlex](https://github.com/ocaml-community/sedlex).

**Comment by favonia** [comment]
Implemented in algaeff.
